name: バグレポート入力フォーム
description: バグレポートを行います
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        このバグレポートにご記入いただきありがとうございます🥹
  - type: textarea
    id: what-happened
    attributes:
      label: どうしたの？
      description: 想定していた動作があれば教えて下さい。
      placeholder: あなたが見たものを教えてください！
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: ログがあれば記載してください
      description: 関連するログ出力をコピーして貼り付けてください。これは自動的にコードにフォーマットされるため、バッククォートは必要ありません。
      render: shell
