name: 検討依頼フォーム
description: GithubIssueFormを使用した検討依頼フォーム
title: "[検討依頼]: "
labels: ["🤔検討","📌タスク"]
body:
  - type: markdown
    attributes:
      value: |
        検討事項を記載します。添付資料などあればURLやファイルを入力前に準備してください🙇‍♂️ 回答は 可能 , 不可能 , 一部条件付きで可能 となります。
  - type: input
    id: contact
    attributes:
      label: 投稿者 (未記入でも可)
      description: 記載内容に不明点や確認事項がある場合の問い合わせ先に使用します
      placeholder: ex. 山田太郎
    validations:
      required: false
  - type: textarea
    id: request-area
    attributes:
      label: どのような検討でしょうか。
      description: 短く、簡潔に、箇条書きで記載してください。
      placeholder: |
        ・記載例：何に対して(プラグイン名やソフト名など) , どのようなとき , どうしたい など記載して下さい。添付資料があればこちらに添付し、用途を記載してください(例:~ P* の ~ を参考にしてください)
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 優先順位
      description: 希望の優先順位を設定してください
      options:
        - 🚗早め(1~2日)
        - 😴急いでない(3~日)
      default: 1
    validations:
      required: true
