name: Core更新時の作業登録
description: WCS_Core更新に関する更新テンプレ
title: "[タスク]:WCS_Core更新作業 "
labels: ["🖊️タスク","✨アップデート"]
body:
  - type: input
    id: update-area
    attributes:
      label: アップデートするバージョンを入力してください
      placeholder: 0.1.1
    validations:
      required: true
  - type: input
    id: url-area
    attributes:
      label: 配布されているパッケージのURLを入力してください
      placeholder: http://www...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        - タスク一覧
  - type: textarea
    id: remarks
    attributes:
      label: その他連絡事項やメモ📝があれば記載ください
      placeholder: メモ内容があれば記載
